### ISSUE TITLE
SQL ERROR

### ISSUE THREAD

**Issue by vanvas** [uran1980/yii2-translate-panel#2]
<h1>Correct, please error</h1>

<b>Column 'id' in where clause is ambiguous</b>
Module: yii2-translate-panel
Model: SourceMessageQuery
<hr>

 <pre>
public function notTranslated()
    {
        $ids = $this->baseQuery()->indexBy('id')->all();
        $this->andWhere(['not in', 'id', array_keys($ids)])
             ->andWhere(['not like', 'message', '@@']);

        return $this;
    }

public function translated()
    {
        $ids = $this->baseQuery()->indexBy('id')->all();
        $this->andWhere(['in', 'id', array_keys($ids)])
             ->andWhere(['not like', 'message', '@@']);

        return $this;
    }
</pre>

must:
 <pre>
'id' -> '`message`.id'
</pre>

Thanks in advance!

**Comment by uran1980** [comment]
@vanvas Can you provide the pull request to fix this issue?

**Comment by ileicovici** [comment]
@uran1980 Please fix this issue

**Comment by uran1980** [comment]
@vanvas, @ileicovici I can't reporoduce this issue. Need more info.

**Comment by ileicovici** [comment]
http://joxi.ru/xAe18VLS3e6kAy

**Comment by ileicovici** [comment]
Now appeared another error
http://joxi.ru/YmEnqvKIgexO26
http://joxi.ru/DrlQEjvh9580mP

**Comment by uran1980** [comment]
fixed in [v0.1.21](https://github.com/uran1980/yii2-translate-panel/releases/tag/v0.1.21)

**Comment by ileicovici** [comment]
Hi. The error still occurs.
http://joxi.ru/zANDQvdfEDanm9
http://joxi.ru/12MDVvWfvjWEmJ
http://joxi.ru/52akJV5f8OXWr0

**Comment by uran1980** [comment]
Please, try to update to [v0.1.22](https://github.com/uran1980/yii2-translate-panel/releases/tag/v0.1.22)

**Comment by ileicovici** [comment]
http://joxi.ru/zANDQvdfEDanm9
http://joxi.ru/MAj1Rj3SzeY82e

**Comment by uran1980** [comment]
Another try [v0.1.23](https://github.com/uran1980/yii2-translate-panel/releases/tag/v0.1.23)

**Comment by ileicovici** [comment]
http://joxi.ru/bmoWBjxfRBbxmy
http://joxi.ru/DrlQEjvh9a1JmP
